### ISSUE TITLE
Running in Docker

### ISSUE THREAD

**Issue by cmptrphreak** [tmcphee/cyberghostvpn#14]
### Describe the issue
Novice here, I am trying to run this in docker compose and so far I was able to make it connect but when I try to console in with portainer I cannot run the status commands. Is there any guidance on running this in docker compose?

### Log / Screenshots

Current service config in yml file : 

  cyberghostvpn:
    container_name: cyberghostvpn
    image: tmcphee/cyberghostvpn:latest
    restart: unless-stopped
    user: $PUID:$PGID
    networks:
      - default
    cap_add:
      - NET_ADMIN
      - MKNOD
    environment:
      - TZ=$TZ
      - ACC=user@mail.com
      - PASS=xxxx
      - COUNTRY=US
      - NETWORK=10.10.0.0/16
      - NAMESERVER=8.8.8.8
    volumes:
      - /dev/net/tun:/dev/net/tun
      - /$DOCKERDIR/cyberghostvpn:/home/root/.cyberghost:rw
      
Log : 

CyberGhostVPN - Docker Edition
----------------------------------------------------------
	Created By: Tyler McPhee
	GitHub: https://github.com/tmcphee/cyberghostvpn
	DockerHub: https://hub.docker.com/r/tmcphee/cyberghostvpn
	
	Ubuntu:20.04 | CyberGhost:1.3.4 | v1.2.1
----------------------------------------------------------
**************User Defined Variables**************
	ACC: [PASSED - NOT SHOWN]
	PASS: [PASSED - NOT SHOWN]

	COUNTRY: US
	NETWORK: 10.10.0.0/16
	NAMESERVER: 8.8.8.8
**************************************************
sysctl: setting key "net.ipv6.conf.all.disable_ipv6", ignoring: Read-only file system
sysctl: setting key "net.ipv6.conf.default.disable_ipv6", ignoring: Read-only file system
sysctl: setting key "net.ipv6.conf.lo.disable_ipv6", ignoring: Read-only file system
sysctl: setting key "net.ipv6.conf.eth0.disable_ipv6", ignoring: Read-only file system
sysctl: setting key "net.ipv4.ip_forward", ignoring: Read-only file system
sudo: you do not exist in the passwd database
Initiating Firewall First Time Setup...
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database
Firewall Setup Complete
/start.sh: line 183: .FIREWALL.cg: Permission denied
Verifying Login Auth...
Passed
Adding network route...
RTNETLINK answers: Operation not permitted
10.10.0.0/16 routed to 172.19.0.1 on eth0
Allowing PORT 53 - IN/OUT
sudo: you do not exist in the passwd database
Blocking PORT 53 - IN/OUT
/start.sh: line 95: /etc/resolv.conf: Permission denied
***********CyberGhost Connection Info***********
	IP: xxxx
	CITY: xxxx
	REGION: xxx

	COUNTRY: xx
	DNS: 127.0.0.11
options ndots:0
************************************************
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database
sudo: you do not exist in the passwd database

Thank you

**Comment by tmcphee** [comment]
Are you running in privileged mode?

**Comment by cmptrphreak** [comment]
I had tried with and without but it looks like my yml file above did not have it added. I added the following a few minute ago but no luck 

   privileged: true

**Comment by cmptrphreak** [comment]
I pulled the user: and it ran as root but im not connecting to the VPN any longer. The error messages did go away and in console I can run #sudo cyberghostvpn --status

**Comment by cmptrphreak** [comment]
Alright, so I got it to work. The priviliged:true needed to be there and I disabled the firewall. I consoled in through portainer and tried a manual connection. It errored out due to CA missing. It kept flipping through gateways and eventually started working. 

Compose service entry : 

 # CyberGhostVPN
   cyberghostvpn:
     container_name: cyberghostvpn
     image: tmcphee/cyberghostvpn:latest
     restart: unless-stopped
     privileged: true
     networks:
       - default
     cap_add:
       - NET_ADMIN
       - MKNOD
     environment:
       - TZ=$TZ
       - ACC=USER@MAIL.COM
       - PASS=XXXXX
       - COUNTRY=US
       - NETWORK=10.10.0.0/16
       - NAMESERVER=8.8.8.8
       - FIREWALL=False
       - WHITELISTPORTS=8080
     ports:
       - 8080:8080
     volumes:
       - /dev/net/tun:/dev/net/tun
       - /$DOCKERDIR/cyberghostvpn:/home/root/.cyberghost:rw
