### ISSUE TITLE
No problem but a question about proxy

### ISSUE THREAD

**Issue by arjanvanleent** [tmcphee/cyberghostvpn#15]
Is it possible to use this docker as a proxy for another PC's so all my browers use this docker as proxy?

**Comment by tmcphee** [comment]
The docker doesn't proxy other PC's. You can find a suitable proxy docker and chain the network to CyberGhost. Use --net=container:cyberghostvpn in the proxy image and set the network to none (Unraid) or equivalent.

https://github.com/tmcphee/cyberghostvpn#how-to-use-this-image

**Comment by tmcphee** [comment]
Ive added a web proxy into an upcoming build. Just testing it before release.

**Comment by tmcphee** [comment]
Proxy is now available.
https://github.com/tmcphee/cyberghostvpn#http-proxy-service
