### ISSUE TITLE
Ignores --city argument when supplied

### ISSUE THREAD

**Issue by Shotz5** [tmcphee/cyberghostvpn#22]
### Describe the issue
The CLI ignores the --city parameter when supplied

### Log / Screenshots
![Screenshot 2023-12-30 183553](https://github.com/tmcphee/cyberghostvpn/assets/72415991/e296eee5-9ee2-424e-99e6-1efcec5342c9)

### Troubleshooting
- Attempted OpenVPN only image
- Attempted barebones execution (only supplied user/pass and --city param)
- Attempted with/without quotes

**Comment by Shotz5** [comment]
My hunch is that it's because in the docs the city always follows the country code in the supplied arguments, that would be shit CLI design, but it's the only issue I can see while rooting through the code (The --county-code arg and $ARGS are separated by the protocol parameter)

**Comment by tmcphee** [comment]
I was investigating the issue. I thought that case as well, but I found CyberGhost needs --country-code and --city.
Unfortunately, this does not work with WireGuard (For me anyway). It does work over OpenVPN with the firewall disabled. 

Currently looking into the firewall and trying to see if CyberGhost needs another IP bypassed

Personally, for faster speeds, I would let it select a random server in Canada. OpenVPN is slow.

**Comment by Shotz5** [comment]
Yeah I experienced that as well. The only other Canadian servers are in Toronto and Montreal which sucks being in Vancouver (talking like halved download speeds at least, even worse on OpenVPN). I've given up on Cyberghost and just got PIA instead and am using the arch-delugevpn package.

Thanks for this package at least! Gave me a fair fight in trying to stay with Cyberghost and not spend needless $$$ but it's CLI is just not good enough.

**Comment by tmcphee** [comment]
I too have given up on CyberGhost and got PIA instead, Cant get the CLI to work anymore. Can only patch holes in a sinking ship for so long.
